services:

  nginx:
    image: nginx # pour que l'image est le meme nom que le service
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - intra_network
    restart: always
    env_file: .env

  wordpress:
    image: wordpress # pour que l'image est le meme nom que le service
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "8010:8010"
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - intra_network
    restart: always
    env_file: .env

  mariadb:
    image: mariadb # pour que l'image est le meme nom que le service
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - intra_network
    restart: always
    env_file: .env

volumes: #ici tu doit specifier un chemin sur la machine hote
  volume_wordpress:
  volume_mariadb:

#exemple
#  volume_wordpress:
#    driver: local
#    driver_opts:
#      type: none
#      o:  bind
#      device: ~/data/wordpress

networks:
  intra_network: